# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 06a641c4ba19ebcacb60e6aaacb0363cf6f61943d673b185ffb3b890df564c520f5b396fc5f8ac12ae9d577b4b79679a01b109256a90bf954efc843a9706d5f6

test:
  secret_key_base: 429ed6902ba9ccbba16abc30e5ee54b55e221119dbe22264cd5dd5246257eb6434af3200c4027c7c3ce5b018e701635732ecb74875a2df0c1cd50336e29119f9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
